library(rJava)
.jinit(parameters="-DrJava.debug=true")
.jaddClassPath('target/debugsqlite-1.1-SNAPSHOT-jar-with-dependencies.jar')
DebugSqlite <- .jnew(class = "com/aliyun/odps/DebugSqlite")
DebugSqlite$testOne()
